name: P_microSALT
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.0
  - blast=2.16.0
  - bwa=0.7.17
  - picard=2.20.3
  - pigz>=2.4
  - quast=5.3.0
  - samtools=1.13
  - trimmomatic=0.39
  - openjdk=11.0.9.1
  - pytest=6.2.5
  - pytest-cov=2.12.1
  - skesa=2.5.1
