name: P_microSALT
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - blast=2.12.0
  - bwa=0.7.17
  - picard=2.20.3
  - pigz=2.4
  - quast=5.0.2
  - samtools=1.13
  - spades=3.13.1
  - trimmomatic=0.39
  - r-base=4.1.1
  - openjdk=11.0.9.1

