---
#SBATCH configuration
slurm_header:
  project: "microbial"
  type: "core"
  threads: "10"
  time: "01:00:00"
  qos: "normal"
  job_name: "MLST_test"

#File finding pattern
file_pattern: '(\d{1}_)?(\d{6})_(\w{9})_(.{3,12})_(\w{8,12}_)?(\d{1})(.fastq.gz)'

#Default file folders
folders:
  installations: "/home/isak.sylvin/CG_MLST/"
  results: "/mnt/hds/proj/cust015/mlst/results"
  references: "/mnt/hds/proj/cust015/mlst/references/definitions_locisplit"
  profiles: "/mnt/hds/proj/cust015/mlst/references/profiles"
