---
#SBATCH configuration
slurm_header:
  project: "microbial"
  type: "core"
  threads: "10"
  time: "01:00:00"
  qos: "normal"
  job_name: "MLST_test"

#Default file folders
folders:
  installations: "/home/isak.sylvin/CG_MLST/"
  #indata: "/home/isak.sylvin/CG_MLST/indata"
  results: "/home/isak.sylvin/CG_MLST/results"
  references: "/home/isak.sylvin/CG_MLST/references/definitions"
  profiles: "/home/isak.sylvin/CG_MLST/references/profiles"
