"""Scrapes output files for data and adds them to the database
By: Isak Sylvin, @sylvinite"""

#!/usr/bin/env python

import glob
import os
import re
import string
import sys
import time

from microSALT.config import (
    Folders,
    Threshold,
    SlurmHeader,
    Regex,
    PubMLSTCredentials,
    PasteurCredentials,
    Singularity,
    Containers,
)
from microSALT.store.db_manipulator import DB_Manipulator
from microSALT.utils.referencer import Referencer
from microSALT.utils.job_creator import Job_Creator


# TODO: Rewrite so samples use seperate objects
class Scraper:
    def __init__(
        self,
        log,
        folders: Folders,
        threshold: Threshold,
        slurm_header: SlurmHeader,
        regex: Regex,
        dry: bool,
        config_path: str,
        pubmlst: PubMLSTCredentials,
        pasteur: PasteurCredentials,
        singularity: Singularity = None,
        containers: Containers = None,
        sampleinfo={},
        input="",
    ):
        self.folders = folders
        self.threshold = threshold
        self.slurm_header = slurm_header
        self.regex = regex
        self.dry = dry
        self.config_path = config_path
        self.pubmlst = pubmlst
        self.pasteur = pasteur
        self.singularity = singularity or Singularity()
        self.containers = containers or Containers()
        self.logger = log
        self.db_pusher = DB_Manipulator(log=log, folders=folders, threshold=threshold)
        self.referencer = Referencer(
            log=log,
            folders=folders,
            threshold=threshold,
            pubmlst=pubmlst,
            pasteur=pasteur,
            singularity=self.singularity,
            containers=self.containers,
        )
        self.job_fallback = Job_Creator(
            log=log,
            folders=folders,
            slurm_header=slurm_header,
            regex=regex,
            dry=dry,
            config_path=config_path,
            threshold=threshold,
            pubmlst=pubmlst,
            pasteur=pasteur,
            singularity=self.singularity,
            containers=self.containers,
            sampleinfo=sampleinfo,
        )
        self.infolder = os.path.abspath(input)
        self.sampledir = ""

        # Since all scraped folders are generated by Job_Creator, datestring is automatically provided in last folder
        last_folder = self.infolder.split("/")[-1]
        self.name = last_folder.split("_")[0]

        self.sampleinfo = sampleinfo
        self.sample = None
        if isinstance(self.sampleinfo, list) and len(self.sampleinfo) > 1:
            self.name = self.sampleinfo[0].get("CG_ID_project")
            self.sample = self.sampleinfo[0]
            for entry in self.sampleinfo:
                if entry.get("CG_ID_sample") == self.name:
                    raise Exception(
                        "Mixed projects in samples_info file. Do not know how to proceed"
                    )
        else:
            if isinstance(self.sampleinfo, list):
                self.sampleinfo = self.sampleinfo[0]
            self.name = self.sampleinfo.get("CG_ID_sample")
            self.sample = self.sampleinfo

        self.gene2resistance = self.load_resistances()

    def scrape_project(self, project=None):
        """Scrapes a project folder for information"""
        if project is None:
            project = self.name
        self.db_pusher.delete_project(project)
        self.job_fallback.create_project(project)

        # Scrape order matters a lot!
        for item in os.listdir(self.infolder):
            sampledir = f"{self.infolder}/{item}"
            if os.path.isdir(sampledir):
                local_param = [p for p in self.sampleinfo if p["CG_ID_sample"] == item]
                if local_param != []:
                    local_param = local_param[0]
                    sample_scraper = Scraper(
                        log=self.logger,
                        folders=self.folders,
                        threshold=self.threshold,
                        slurm_header=self.slurm_header,
                        regex=self.regex,
                        dry=self.dry,
                        config_path=self.config_path,
                        pubmlst=self.pubmlst,
                        pasteur=self.pasteur,
                        sampleinfo=local_param,
                        input=sampledir,
                    )
                    sample_scraper.scrape_sample()
                else:
                    self.logger.warning(f"Skipping {dir} due to lacking info in sample_json file")

    def scrape_sample(self, sample=None):
        """Scrapes a sample folder for information"""
        if sample is None:
            sample = self.name
        self.db_pusher.delete_sample_results(sample)
        self.job_fallback.create_project(self.sample.get("CG_ID_project"))
        self.job_fallback.create_sample()

        # Scrape order matters a lot!
        self.sampledir = self.infolder
        self.scrape_blast(type="seq_type")
        self.scrape_blast(type="resistance")
        if self.referencer.organism2reference(self.sample.get("organism")) == "escherichia_coli":
            self.scrape_blast(type="expec")
        self.scrape_alignment()
        self.scrape_quast()
        self.scrape_reference()

    def scrape_quast(self, filename=""):
        """Scrapes a quast report for assembly information"""
        if filename == "":
            filename = f"{self.sampledir}/assembly/quast/{self.name}_report.tsv"
            if not os.path.isfile(filename):
                filename = f"{self.sampledir}/assembly/quast/report.tsv"

        quast = dict()
        try:
            with open(filename, "r") as infile:
                for line in infile:
                    lsplit = line.rstrip().split("\t")
                    if lsplit[0] == "# contigs":
                        quast["contigs"] = int(lsplit[1])
                    elif lsplit[0] == "Total length":
                        quast["genome_length"] = int(lsplit[1])
                    elif lsplit[0] == "GC (%)":
                        quast["gc_percentage"] = float(lsplit[1])
                    elif lsplit[0] == "N50":
                        quast["n50"] = int(lsplit[1])

            self.db_pusher.update_sample({"CG_ID_sample": self.name}, quast)
            self.logger.debug(f"Project {self.name} recieved quast stats: {quast}")
        except Exception as e:
            self.logger.warning(f"Cannot generate quast statistics for {self.name}")

    def scrape_reference(self) -> None:
        """Scrapes a reference assembly to calculate the size"""
        assembly = (
            f"{self.sampledir}/../../../references/genomes/{self.sample.get('reference')}.fasta"
        )
        if not os.path.exists(assembly):
            assembly = (
                f"{self.sampledir}/../../references/genomes/{self.sample.get('reference')}.fasta"
            )
        reference_data = dict()
        try:
            with open(assembly, "r") as infile:
                assembly_length = 0
                for line in infile:
                    if not line.startswith(">"):
                        curated_line = line.strip()
                        assembly_length += len(curated_line)
                reference_data["reference_length"] = assembly_length
            self.db_pusher.update_sample({"CG_ID_sample": self.name}, reference_data)
            self.logger.debug(f"Project {self.name} recieved quast stats: {reference_data}")
        except Exception as e:
            self.logger.warning(f"Cannot find assembly size for reference {self.name}")

    def get_locilengths(self, foldername, suffix):
        """Generate a dict of length for any given loci"""
        # Create dict with full name as key, associated nucleotides as value.
        alleles = dict()
        finalalleles = dict()
        for file in os.listdir(foldername):
            if file.endswith(suffix):
                lastallele = ""
                f = open(f"{foldername}/{file}", "r")
                for row in f:
                    if ">" in row:
                        lastallele = row.strip()
                        alleles[lastallele] = ""
                    else:
                        alleles[lastallele] = alleles[lastallele] + row.strip()
                f.close()

                for k, v in alleles.items():
                    finalalleles[k] = len(v)
        return finalalleles

    def scrape_blast(self, type="", file_list=[]):
        organism = self.referencer.organism2reference(self.sample.get("organism"))
        if organism:
            self.db_pusher.update_sample({"CG_ID_sample": self.name}, {"organism": organism})
        type2db = "Expacs" if type == "expec" else type.capitalize() + "s"
        if not file_list:
            file_list = self._resolve_blast_files(type, organism)
        hits = self._parse_blast_files(type, file_list, organism)
        identifier = "loci" if type == "seq_type" else "gene"
        hits = self._deduplicate_hits(hits, identifier)
        self._persist_blast_hits(type, type2db, hits)
        return hits

    def _resolve_blast_files(self, type: str, organism: str) -> list:
        """Resolves which blast output files to parse for a given type."""
        if type == "seq_type":
            return glob.glob(f"{self.sampledir}/blast_search/mlst/*")
        return glob.glob(f"{self.sampledir}/blast_search/{type}/*")

    def _resolve_ref_folder_and_suffix(self, type: str, organism: str) -> tuple:
        """Returns the reference folder and file suffix for locilength lookup."""
        if type == "resistance":
            return self.folders.resistances, "fsa"
        elif type == "expec":
            return (
                os.path.dirname(self.folders.expec),
                os.path.basename(self.folders.expec).rsplit(".", 1)[1],
            )
        else:  # seq_type
            return f"{self.folders.references}/{organism}", "tfa"

    def _parse_common_fields(self, elem_list: list) -> dict:
        """Parses the fields shared across all BLAST hit types from one TSV line."""
        if int(elem_list[7]) < int(elem_list[8]):
            contig_start, contig_end = int(elem_list[7]), int(elem_list[8])
        else:
            contig_start, contig_end = int(elem_list[8]), int(elem_list[7])
        nodeinfo = elem_list[2].split("_")
        return {
            "CG_ID_sample": self.name,
            "identity": elem_list[4],
            "evalue": elem_list[5],
            "bitscore": elem_list[6],
            "subject_length": int(elem_list[11]),
            "contig_start": contig_start,
            "contig_end": contig_end,
            "contig_name": f"{nodeinfo[0]}_{nodeinfo[1]}",
            "contig_length": int(nodeinfo[3]),
            "contig_coverage": nodeinfo[5],
        }

    def _parse_resistance_hit(
        self, hit: dict, filename: str, elem_list: list, locilengths: dict
    ) -> dict:
        """Enriches a hit dict with resistance-specific fields."""
        hit["instance"] = filename
        partials = re.search(r"(?:>)*(.+)_(\d+){1,3}_(.+)", elem_list[3])
        hit["reference"] = partials.group(3)
        hit["gene"] = partials.group(1)
        hit["resistance"] = self.gene2resistance.get(hit["gene"], hit["instance"].capitalize())
        padder = [x for x in locilengths if x.startswith(f">{partials.group(1)}_")]
        if not padder:
            padder = [x for x in locilengths if x.startswith(f">{partials.group(1)[:-1]}_")]
        try:
            padder = padder[0]
        except IndexError:
            self.logger.warning(
                f"In {self.name} gene {partials.group(1)} can't be resolved. Wrong resistance?"
            )
        hit["span"] = float(hit["subject_length"]) / locilengths[padder]
        return hit

    def _parse_expec_hit(
        self, hit: dict, filename: str, elem_list: list, locilengths: dict
    ) -> dict:
        """Enriches a hit dict with ExPEC-specific fields."""
        hit["instance"] = filename
        # Thanks, precompiled list standards
        if ">" in elem_list[3]:
            partials = re.search(
                r">*(\w+_\w+\.*\w+).+\((\w+)\).+\((\w+)\)_(\w+)_\[.+\]",
                elem_list[3],
            )
        else:
            partials = re.search(
                r"(\w+)\(gb\|\w+\)_\((\S+)\)_(.+)_\[(\S+)_.+\]_\[\S+\]",
                elem_list[3],
            )
        if not partials:
            partials = re.search(
                r"(\w+\.*\w+)\:*\w*_*(?:\(\w+\-\w+\))*_\((\w+)\)_([^[]+)\[\S+\]",
                elem_list[3],
            )
        hit["reference"] = partials.group(1)
        hit["gene"] = partials.group(2)
        hit["instance"] = partials.group(3).strip("_")
        hit["virulence"] = (
            partials.group(4).replace("_", " ").capitalize() if len(partials.groups()) >= 4 else ""
        )
        hit["span"] = float(hit["subject_length"]) / locilengths[f">{elem_list[3]}"]
        return hit

    def _parse_seq_type_hit(self, hit: dict, elem_list: list, locilengths: dict) -> dict:
        """Enriches a hit dict with seq_type (MLST) specific fields."""
        partials = re.search(r"(.+)_(\d+){1,3}(?:_(\w+))*", elem_list[3])
        hit["loci"] = partials.group(1)
        hit["allele"] = int(partials.group(2))
        padder = [x for x in locilengths if x.startswith(f">{partials[0]}")]
        if not padder:
            padder = [x for x in locilengths if x.startswith(f">{partials[0][:-1]}")]
        try:
            padder = padder[0]
        except IndexError:
            self.logger.warning(
                f"In {self.name} allele {partials[0]} can't be resolved. Wrong organism?"
            )
        hit["span"] = float(hit["subject_length"]) / locilengths[padder]
        return hit

    def _parse_blast_files(self, type: str, file_list: list, organism: str) -> list:
        """Parses all blast output files and returns a list of candidate hit dicts."""
        type2db = "Expacs" if type == "expec" else type.capitalize() + "s"
        ref_folder, suffix = self._resolve_ref_folder_and_suffix(type, organism)
        locilengths = self.get_locilengths(ref_folder, suffix)
        hits = []
        try:
            for file in file_list:
                filename = os.path.basename(file).rsplit(".", 1)[0]  # Removes suffix
                if filename == "lactam":
                    filename = "beta-lactam"
                with open(file, "r") as fh:
                    for line in fh:
                        if line[0] == "#":
                            continue
                        elem_list = line.rstrip().split("\t")
                        if elem_list[1] == "N/A":
                            continue
                        hit = self._parse_common_fields(elem_list)
                        if type == "resistance":
                            hit = self._parse_resistance_hit(hit, filename, elem_list, locilengths)
                        elif type == "expec":
                            hit = self._parse_expec_hit(hit, filename, elem_list, locilengths)
                        elif type == "seq_type":
                            hit = self._parse_seq_type_hit(hit, elem_list, locilengths)
                        self.logger.debug(f"scrape_blast scrape loop hit '{elem_list[3]}'")
                        hits.append(hit)
            self.logger.info(f"{len(hits)} candidate {type2db} hits found")
        except Exception as e:
            self.logger.error(f"Unable to process the pattern of {e!s}")
        return hits

    def _deduplicate_hits(self, hits: list, identifier: str) -> list:
        """Removes overlapping or duplicate BLAST hits, keeping the highest-scoring one."""
        ind = 0
        while ind < len(hits) - 1:
            targ = ind + 1
            while targ < len(hits):
                ignore = False
                if (
                    hits[ind]["contig_name"] == hits[targ]["contig_name"]
                    or hits[ind][identifier] == hits[targ][identifier]
                ):
                    # Overlapping or shared gene/loci
                    if (
                        (
                            hits[ind].get("contig_start") >= hits[targ].get("contig_start")
                            and hits[ind].get("contig_start") <= hits[targ].get("contig_end")
                        )
                        or (
                            hits[ind].get("contig_end") >= hits[targ].get("contig_start")
                            and hits[ind].get("contig_end") <= hits[targ].get("contig_end")
                        )
                        or (hits[ind].get(identifier) == hits[targ].get(identifier))
                    ):
                        score_ind = float(hits[ind]["identity"]) * (1 - abs(1 - hits[ind]["span"]))
                        score_targ = float(hits[targ]["identity"]) * (
                            1 - abs(1 - hits[targ]["span"])
                        )
                        # Rightmost is worse
                        if score_ind > score_targ:
                            del hits[targ]
                            ignore = True
                        # Leftmost is worse
                        elif score_ind < score_targ:
                            del hits[ind]
                            targ = ind + 1
                            ignore = True
                        # Identical score — break tie by contig coverage
                        else:
                            if float(hits[ind]["contig_coverage"]) >= float(
                                hits[targ]["contig_coverage"]
                            ):
                                del hits[targ]
                                ignore = True
                            elif float(hits[ind]["contig_coverage"]) < float(
                                hits[targ]["contig_coverage"]
                            ):
                                del hits[ind]
                                targ = ind + 1
                                ignore = True
                if not ignore:
                    targ += 1
            ind += 1
        return hits

    def _persist_blast_hits(self, type: str, type2db: str, hits: list) -> None:
        """Writes deduplicated blast hits to the database and updates sample ST if applicable."""
        _ADDERS = {
            "Seq_types": self.db_pusher.add_seq_type,
            "Resistances": self.db_pusher.add_resistance,
            "Expacs": self.db_pusher.add_expac,
        }
        self.logger.info(
            f"{len(hits)} {type} hits were added after removing overlaps and duplicate hits"
        )
        for hit in hits:
            self.logger.debug(
                f"Kept {hit.get('loci')}:{hit.get('allele')} with span {hit.get('span')} and id {hit.get('identity')}"
            )
            self.db_pusher.add_to_session(_ADDERS[type2db](**hit))
        self.db_pusher.commit_session()
        if type == "seq_type":
            try:
                ST = self.db_pusher.read_st(self.name)
                self.db_pusher.update_sample({"CG_ID_sample": self.name}, {"ST": ST})
                self.logger.info(f"Sample {self.name} received ST {ST}")
            except Exception as e:
                self.logger.warning(f"Unable to type sample {self.name} due to data value '{e!s}'")

    def load_resistances(self):
        """Legacy function, loads common resistance names for genes from notes file"""
        conversions = dict()
        try:
            with open(f"{self.folders.resistances}/notes.txt") as fh:
                for line in fh:
                    if "#" not in line:
                        line = line.split(":")
                        cropped = re.sub(" resistance", "", line[1])
                        conversions[line[0]] = cropped
                        # Workaround for case issues
                        conversions[line[0].lower()] = cropped
        except Exception as e:
            self.logger.error(f"Unable to initialize trivial names for resistances ({e})")
        return conversions

    def scrape_alignment(self, file_list=[]):
        """Scrapes a single alignment result"""
        if file_list == []:
            file_list = glob.glob(f"{self.sampledir}/alignment/*.stats.*")
        ins_list = list()
        cov_dict = dict()
        align_dict = dict()
        align_dict["reference_genome"] = self.sample.get("reference")

        # Reading
        map_rate = 0.0
        median_ins = 0
        ref_len = 0.0
        tot_reads = 0
        tot_map = 0
        duprate = 0.0
        for file in file_list:
            with open(file, "r") as fh:
                type = file.split(".")[-1]
                for line in fh.readlines():
                    lsplit = line.rstrip().split("\t")
                    if type == "raw":
                        try:
                            tot_reads = int(lsplit[0])
                        except Exception as e:
                            pass
                    elif type == "ins":
                        if len(lsplit) >= 18 and lsplit[-12] in ["FF", "FR"]:
                            try:
                                median_ins = int(lsplit[0])
                            except Exception as e:
                                pass
                    elif type == "cov":
                        cov_dict[lsplit[1]] = int(lsplit[2])
                    elif type == "ref":
                        if lsplit[0] != "*" and len(lsplit) >= 2:
                            ref_len = ref_len + int(lsplit[1])
                    elif type == "dup":
                        if lsplit[0] == "Unknown Library":
                            try:
                                duprate = float(lsplit[8])
                            except Exception as e:
                                duprate = -1.0
                    elif type == "map":
                        dsplit = line.rstrip().split(" ")
                        if len(dsplit) >= 5 and dsplit[4] == "total":
                            tot_map = int(dsplit[0])
                        elif len(dsplit) >= 4 and dsplit[3] == "mapped":
                            if tot_map > 0:
                                map_rate = int(dsplit[0]) / float(tot_map)

        # Mangling
        sumz, plus10, plus30, plus50, plus100, total = 0, 0, 0, 0, 0, 0
        for k, v in cov_dict.items():
            sumz += int(k) * v
            total += v
            if int(k) > 10:
                plus10 += v
            if int(k) > 30:
                plus30 += v
            if int(k) > 50:
                plus50 += v
            if int(k) > 100:
                plus100 += v
        if total > 0:
            align_dict["coverage_10x"] = plus10 / float(ref_len)
            align_dict["coverage_30x"] = plus30 / float(ref_len)
            align_dict["coverage_50x"] = plus50 / float(ref_len)
            align_dict["coverage_100x"] = plus100 / float(ref_len)
        else:
            align_dict["coverage_10x"] = 0.0
            align_dict["coverage_30x"] = 0.0
            align_dict["coverage_50x"] = 0.0
            align_dict["coverage_100x"] = 0.0

        align_dict["mapped_rate"] = map_rate
        align_dict["insert_size"] = median_ins
        if ref_len > 0:
            align_dict["duplication_rate"] = duprate
            align_dict["average_coverage"] = sumz / float(ref_len)
        else:
            align_dict["duplication_rate"] = 0.0
            align_dict["average_coverage"] = 0.0
        align_dict["total_reads"] = tot_reads
        self.db_pusher.update_sample({"CG_ID_sample": self.name}, align_dict)
